### ISSUE TITLE
Explanation of diff resolving

### ISSUE THREAD

**Issue by 2400mills** [cm226/y-textarea#1]
Hi! Thanks a ton for this library! I was wondering if you could explain the core of how this code works? I'm having a bit of a hard time understand CRDT's in general

```
const r = this.createRange(textField);
                        
let oldContent = yText.toString()
let content = textField.value
let diffs = diff(oldContent, content, r.left)
let pos = 0
for (let i = 0; i < diffs.length; i++) {
    let d = diffs[i]
    if (d[0] === 0) { // EQUAL
        pos += d[1].length
    } else if (d[0] === -1) { // DELETE
        yText.delete(pos, d[1].length)
    } else { // INSERT
        yText.insert(pos, d[1])
        pos += d[1].length
    }
}
```

The behavior of `yText.delete()` and `yText.insert()` in the yjs library is a bit strange to me. If I had a `Y.Text()` variable named yText whose .toString() returned "abc", I would expect `yText.insert(0, "d")` and a subsequent `yText.toString()` to return "dabc". Then, I would expect `yText.delete(0, 1)` and `yText.toString()` to return "abc", but this doesn't seem to be the case.

**Comment by cm226** [comment]
Hi, you would be better asking your question on https://discuss.yjs.dev/.
This project is an addon to yjs to bind a Y.Text to a textarea, your question seems more related to the Y.Text datatype.
