### ISSUE TITLE
Cursor is shifted when selecting text in local textarea and replacing it

### ISSUE THREAD

**Issue by cavenel** [cm226/y-textarea#12]
When selecting text, and pasting or typing new text, the cursors jumps forward.
One reason is that selecting and replacing text ends up as "delete" followed by "insert" in the diff, which makes two `yText` modifications.
And as the `textfieldChanged` is only put to `true` once, it is put back to `false` on the first `yText` modification. This ends up triggering a non-local modification in `yTextObserver ` on the second modification.

Not sure why this non-local modification ends up as a cursor shift, but putting `textfieldChanged = true` before each `yText` modification fixes it.
I made a PR with this fix here: https://github.com/cm226/y-textarea/pull/11

**Comment by cm226** [comment]
Hi @cavenel, Thanks for the PR!

I think your right, there does seem to be an issue here, with multiple local changes messing with the cursor position logic. 

It looks like your changes may fix the issue, although I think those changes rely on Y.js local changes always being applied synchronously, which I think they will, to be fair. 

An alternative approach, which I think might be better is to wrap the changes in a transaction

```
doc.transact(tr => {
        for (let i = 0; i < diffs.length; i++) {
          let d = diffs[i]
          if (d[0] === 0) {
            // EQUAL
            pos += d[1].length
          } else if (d[0] === -1) {
            // DELETE
            yText.delete(pos, d[1].length)
          } else {
            // INSERT
            yText.insert(pos, d[1])
            pos += d[1].length
          }
        }
      })
```
This approach looked like it was also solving the issue for me.
Let me know if it works for you?

**Comment by cavenel** [comment]
That works perfectly with me indeed, well thought :)
I updated my PR but feel free to just edit this directly, as I had to revert my old commit.

**Comment by cm226** [comment]
Thanks for that, Merged now.
