### ISSUE TITLE
Wrong cursor position for nested TextArea

### ISSUE THREAD

**Issue by benediktniedernhuber** [cm226/y-textarea#4]
Currently cursors and nametags are always attached to the document.body, while offsetTop and offsetLeft are used calculate
the absolute position of the cursors. offsetTop and offsetLeft are relative to the TextArea's offsetParent, which isn't always the document.body [https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetParent](url). If the TextArea is nested inside a e.g. a different non-statically positioned element, the offsetParent will be that element and not the document.body, which ultimately leads to cursors being rendered in the wrong place. 
Attaching the cursors and nametags to the offsetParent instead of the document.body would be a possible fix for this issue. 
I'd be happy to provide a PR for this.

**Comment by cm226** [comment]
hey @benediktniedernhuber Thanks for pointing that out. 

If the offsetParent thing works and you raise a PR then Im happy to merge. If not it will probably be the weekend before i get a chance to look at this.
