### ISSUE TITLE
Sanitise cursor names

### ISSUE THREAD

**Issue by yousefamar** [cm226/y-textarea#8]
At the moment, it's possible for a user to set their name as arbitrary HTML. Script tags don't seem to quite work, so this is not an XSS problem I think, but a malicious user could troll people by e.g. setting their name as a Rick Roll Youtube embed, or something more nefarious.

```
<iframe width="560" height="315" src="https://www.youtube.com/embed/dQw4w9WgXcQ"></iframe>
```

![image](https://user-images.githubusercontent.com/999235/212791453-50338ac8-5713-41aa-acd4-4a0b6ab1734d.png)

**Comment by cm226** [comment]
Hi @yousefamar 

Interesting, my initial thought was that thats not something I really want to try and deal with in this lib. But with the current api there is probably no way for users to prevent this. Need to have a think about this one.
Thanks for pointing it out!

**Comment by yousefamar** [comment]
No problem! I didn't make a PR because I wasn't sure if you'd want this (maybe there's a legitimate use case like styling specific names?) but if you wanted to make this optional with a flag or something, I think the only required change would be to default `innerHTML` to `innerText` inside Cursor, which would turn any special characters into HTML entities. Tbh I'm not sure the use case I mentioned is real.

**Comment by cm226** [comment]
Hey thanks for this sorry for taking so long. Just decided that your right, that use case probably doesn't exist. fixed now. Thanks
