### ISSUE TITLE
input or textarea element must have an explicit CSS "position" setting

### ISSUE THREAD

**Issue by rozek** [cm226/y-textarea#9]
Just a minor issue: in order for foreign cursors and text selections to appear at their proper position, the shared input or textarea element must have an explicit CSS "position" setting, e.g.

```
  <textarea style="position:relative"></textarea>
```

The default setting ("static") does not work.

**Comment by cm226** [comment]
Hi, @rozek. I think there might be something else going on. The demo app cursors seem to be positioning correctly, the TextArea element is using the default position CSS. 

You can test for yourself by starting yjs :
HOST=localhost PORT=1234 npx y-websocket-server
then running the demo app 
npm run dev
